### PR TITLE
[breaking] Update ember cli to 3.28

### PR DESCRIPTION
**Pull request by jrjohnson**
Breaking Changes: 
- Drops support for Node < 12
- Requires consuming apps to use ember-auto-import v2

Otherwise this is just a blueprint and dependency update plus moving CI from Travis (which doesn't work anymore) to GitHub Actions.

### CODE REVIEW

**Comment by blimmer** [comment]
Hey @jrjohnson - thanks for taking the time to contribute! I pulled down this code and it seems reasonable to me. To be fully transparent, I haven't used Ember in several years, so I haven't kept up with the changes over the last few years. Since these changes all seem fairly boilerplate, I'd be happy to merge this contribution once the PR is ready for review.

**Comment by jrjohnson** [comment]
Thanks @blimmer. It's ready for merging. I have permission to merge it here, if you want to add `jrjohnson` to NPM as well I can manage the release. Whatever works best for you.

**Review by blimmer — APPROVED** [review]

**Comment by blimmer** [comment]
This is published as version 3.0.0 - thanks!

**Comment by jrjohnson** [comment]
Thank you!

**Pull request merged**
